{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "researcherai.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "researcherai.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app: researcherai-multiagent
      {{- include "researcherai.selectorLabels" . | nindent 6 }}
{{- end }}
